<?php
$this->load->view('header/header');
$csrfName = $this->security->get_csrf_token_name();
$csrfHash = $this->security->get_csrf_hash();
?>
<div
  data-cams-modal-content
  data-modal-title="Reset Physician Password"
  data-modal-eyebrow="Account recovery"
  data-modal-description="Generate a secure temporary password for this physician account."
  data-modal-width="620px"
>
  <form
    action="<?=base_url('Admin/PhysicianUpdate')?>"
    method="post"
    class="space-y-5"
    data-cams-ajax="true"
    data-keep-open-on-success="true"
    data-confirm-title="Reset this physician's password?"
    data-confirm-text="The current password will be replaced by the generated temporary password."
    data-confirm-button="Yes, reset password"
    data-success-title="Temporary password activated"
  >
    <input type="hidden" name="old_physician_id" value="<?=htmlspecialchars((string)$old_physician_id, ENT_QUOTES, 'UTF-8')?>">
    <input type="hidden" name="reset_token" value="<?=htmlspecialchars((string)$resetToken, ENT_QUOTES, 'UTF-8')?>" data-cams-reset-token>
    <input type="hidden" name="<?=htmlspecialchars($csrfName, ENT_QUOTES, 'UTF-8')?>" value="<?=htmlspecialchars($csrfHash, ENT_QUOTES, 'UTF-8')?>">

    <div class="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">
      <div class="flex gap-3">
        <i class="fa fa-key mt-0.5 text-amber-600"></i>
        <div>
          <strong class="block">Temporary sign-in credential</strong>
          <span class="mt-1 block leading-6">This password is generated by CAMS and will replace the physician's current password after you confirm the reset. Ask the physician to change it after signing in.</span>
        </div>
      </div>
    </div>

    <div>
      <label for="cams-temp-password" class="mb-2 block text-sm font-extrabold text-slate-700">System-generated temporary password</label>
      <div class="flex gap-2">
        <input id="cams-temp-password" type="text" class="form-control !min-h-12 !text-lg !font-bold !tracking-wide" value="<?=htmlspecialchars((string)$temporaryPassword, ENT_QUOTES, 'UTF-8')?>" readonly data-cams-temp-password>
        <button type="button" class="btn btn-default !min-h-12 shrink-0" data-cams-copy-temp title="Copy temporary password"><i class="fa fa-copy"></i> Copy</button>
      </div>
      <p class="mb-0 mt-2 text-sm text-slate-500">The generated credential is valid for this reset request for 10 minutes.</p>
    </div>

    <button type="button"
            class="btn btn-default !min-h-11"
            data-cams-regenerate-temp
            data-url="<?=htmlspecialchars($regenerateUrl, ENT_QUOTES, 'UTF-8')?>">
      <i class="fa fa-refresh"></i>
      Generate Another Password
    </button>

    <div class="hidden rounded-2xl border border-emerald-200 bg-emerald-50 p-4" data-cams-reset-result>
      <strong class="block text-emerald-800">Temporary password is now active.</strong>
      <p class="mb-0 mt-1 text-sm text-emerald-700">Copy the password above and provide it securely to the physician.</p>
    </div>

    <div class="flex justify-end border-t border-slate-100 pt-5">
      <button type="submit" class="btn btn-primary !min-h-11">
        <i class="fa fa-key"></i>
        Generate & Reset Password
      </button>
    </div>
  </form>
</div>
</body>
</html>